### ISSUE TITLE
Fix Coordinating Committee Images

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/ndsa.org#10]
Standardize the size of the Coordinating Committee images.

**Comment by waynegraham** [comment]
The images on the thumb drive are the same as I have; @ohbendorf @nowviskie we can do research/ask for larger ones, but there's not much that can be done with these images.

**Comment by ohbendorf** [comment]
@waynegraham, I just dropped into their respective folders from the thumb drive what are possibly higher res versions of the pictures of Helen Tibbo and Jim Corridan. The picture we have of Jonathan Crabtree is 1.3mb so we might be able to size it up on the page.
