### ISSUE TITLE
Update Header Navigation

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/ndsa.org#11]
Get the navigation system filled out with assistance from @ohbendorf

**Comment by ohbendorf** [comment]
About
-FAQ
-Values
-Coordinating Committee

Activities
-National Agenda
-Awards
-Calendar
-Wiki
[Horizontal Line]
Nav header: Resources
-Case Studies
-Levels of Digital Preservation
-Glossary
(I realize most of those "resources" are also listed on the main "Activities" page-- so is it redundant to put them here / does it make the drop-down menu too long?)

Members
-Member List
-Expert Guide
-New Member Orientation
-Get Involved

Working Groups
-Content
-Standards and Practices
-Infrastructure
-Innovation
-Outreach
