### ISSUE TITLE
Update Footer Information

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/ndsa.org#12]
Finalize footer information with input form @ohbendorf

**Comment by ohbendorf** [comment]
Bethany suggests a Scholars' Lab type of Creative Commons footer, rather than a copyright.

**Comment by waynegraham** [comment]
Did you discuss with @nowviskie the footer content blocks?

**Comment by nowviskie** [comment]
Fine with me, although I'm not sure what you have in mind for "Terms and Conditions" and "Privacy Policy." Necessary? And this is just a reminder that Micah would prefer CC-BY-SA to a pure CC-BY. Thanks! (I'll do a big content once-over whenever you and @ohbendorf tell me you're basically done and ready for that!)

**Comment by waynegraham** [comment]
@nowviskie those two were more filler than anything else; the **Social** needs to be updated too as they basically have Twitter, so there may be something more appropriate there

Updated Copyright is in #20

**Comment by nowviskie** [comment]
Oliver can make a judgment call, but there may be some appropriate blended NDSA/NDIIPP social media content on YouTube and iTunes U, especially coming out of the Digital Preservation meetings. See footer: http://www.digitalpreservation.gov/ndsa/

**Comment by waynegraham** [comment]
I'm going to reassign this ticket to @ohbendorf

**Comment by waynegraham** [comment]
I moved some things around in the footer; mind checking it out @ohbendorf @nowviskie?

**Comment by nowviskie** [comment]
Approved! Thank you! Before you close the ticket, let's please take advantage of the space beneath the footer NDSA logo to add the text (with a link) "The National Digital Stewardship Alliance is proudly hosted by the Digital Library Federation."

**Comment by ohbendorf** [comment]
Looks great, @waynegraham .
