### ISSUE TITLE
Thumbnail images for landing page

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/ndsa.org#19]
Need actual image assets for 
- Get Involved
- National Agenda
- Coordinating Committee
- Awards

**Comment by ohbendorf** [comment]
@waynegraham, here are my picks from font-awesome for eight possible pages. Is that too many, visually, for that area to be effective in featuring them? If so, I can eliminate some.

Get Involved:
plug
institution

National Agenda
arrow-circle-right
globe
binoculars

Coordinating Committee
group (don't love that one of the people is bigger/foregrounded, though)
object-group

Wiki
folder-open
files-o

Awards
bookmark
bolt

Levels of Digital Preservation
sort-amount-desc
sliders

Calendar
calendar

Annual Meeting
comments
cubes

**Comment by waynegraham** [comment]
closed in dc742cf19a901223b7f0ef3909ff137c856dec03
