### ISSUE TITLE
create Meetings page

### ISSUE THREAD

**Issue by ohbendorf** [clirdlf/ndsa.org#21]

**Comment by waynegraham** [comment]
[ ] Make a mirror of the content
[ ] Find useful meeting info for NDSA

`$ wget --mirror http://www.digitalpreservation.gov/meetings/`
`$ ag ndsa`

**Comment by waynegraham** [comment]
There's a meeting page, but what needs to go on it?

**Comment by ohbendorf** [comment]
@waynegraham I would say three main things, which I can help flesh out, but in terms of structure:

1) information about upcoming DigiPres, with possibly a link to https://www.diglib.org/forums/2016forum/

2) links to past DigiPres meetings and other annual meetings (listed here http://www.digitalpreservation.gov/meetings/)

3) a link to the calendar of regular working group meetings and other events (http://ndsa.diglib.org/calendar/)

**Comment by ohbendorf** [comment]
![coordinatingcommittee](https://cloud.githubusercontent.com/assets/14017120/11905691/d41d11c6-a595-11e5-9acd-3375b68fcd3d.png)
![calendar](https://cloud.githubusercontent.com/assets/14017120/11905698/d94e68e8-a595-11e5-859e-2bb8964362bc.png)
![annual meeting](https://cloud.githubusercontent.com/assets/14017120/11905700/ddabd7cc-a595-11e5-8b14-7d6acfaaa063.png)
![wiki](https://cloud.githubusercontent.com/assets/14017120/11905703/e2277d60-a595-11e5-9c60-598654a60970.png)
![awards](https://cloud.githubusercontent.com/assets/14017120/11905718/f165dab0-a595-11e5-9604-c33bf7b7a41a.png)
![getinvolved](https://cloud.githubusercontent.com/assets/14017120/11905719/f1675c82-a595-11e5-9587-e594ecf927d2.png)
![levels](https://cloud.githubusercontent.com/assets/14017120/11905721/f16ad2cc-a595-11e5-9e07-9e9ec0e61b67.png)
![nationalagenda](https://cloud.githubusercontent.com/assets/14017120/11905720/f167d2b6-a595-11e5-8101-1b0431f6bba6.png)

**Comment by waynegraham** [comment]
@ohbendorf anything else needed on this page?

**Comment by ohbendorf** [comment]
@waynegraham Nothing is necessarily missing, but it's obviously barebones at the moment and I will add some more content yet today or tomorrow at the latest. I might want to include links to previous Digital Preservation meetings, even though I know they're all listed at the .gov page that's linked to.
