### ISSUE TITLE
connect top-level pages to menu

### ISSUE THREAD

**Issue by nowviskie** [clirdlf/ndsa.org#29]
Not sure if you're aware, but top-level pages for each menu heading (like http://ndsa.diglib.org/working-groups/ or http://ndsa.diglib.org/about/) are not accessible from the menu itself. Since clicking opens the drop-down, how about replicating them as the top item in each drop-down? 

Content is starting to look really good! I mentioned to Wayne that I'll do a big once-over and final edit when you let me know that you're finished.

**Comment by waynegraham** [comment]
If it's helpful, the sitemap (http://ndsa.diglib.org/sitemap.xml) has a listing of all the pages so you don't have to dig through the slug headers.
