### ISSUE TITLE
Find and fix issue with divs animating twice on page load 

### ISSUE THREAD

**Issue by ohbendorf** [clirdlf/ndsa.org#41]
Pages: /index, /coordinating-committee, and /working-groups. As described by @nowviskie: "It slides about halfway in and then, as the full content for the page loads, starts its slide again."

**Comment by nowviskie** [comment]
May just want to see if adding some time to the delay avoids the issue without being too distracting. I tested a bit and don't see it happening on the div timed to .3s.
