### ISSUE TITLE
values commitment in membership application

### ISSUE THREAD

**Issue by nowviskie** [clirdlf/ndsa.org#42]
Ask people to affirm their institution's commitment to the NDSA values statement (with link: http://ndsa.diglib.org/values/) on the membership application form. Checkbox is okay.

**Comment by ohbendorf** [comment]
View updated form at: https://docs.google.com/forms/d/1hcndPYdqRjcTyaq0dP3uZZzg2nKG35mC6xUZIBl9e_U/viewform

**Comment by nowviskie** [comment]
Perfect; thanks!
