### ISSUE TITLE
Update members list with current data

### ISSUE THREAD

**Issue by ohbendorf** [clirdlf/ndsa.org#44]
Most current members list (attached spreadsheet) has over 190 members; this one is displaying 166.
[NDSA_Members_current.xlsx](https://github.com/clirdlf/ndsa.org/files/89418/NDSA_Members_current.xlsx)

**Comment by waynegraham** [comment]
@ohbendorf Ran in to a bit of an issue in that this spreadsheet doesn't contain the **Focus** field that I used to generate the table grid view. I can regenerate the map from this data, but the table view of information will look broken as this information is missing. Might be better to hold off on this one until #37 is closed so we have one datasource with all the information.

**Comment by waynegraham** [comment]
closed in 1100db7
