### ISSUE TITLE
Automated Reminders

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/ndsa.org#52]
Because importing the information is a manual task, we need some method of notifying someone to run the `import:rss` task. Some things to investigate:

- When a new item is found in the ndsa feed, notify the #ndsa Slack channel (like a IFTTT script or web hook or something)
- Notes for authors (or people in charge of this) to notify/run the script

**Comment by kimnkl** [comment]
I think I'll be the one running the script for now. I've given NDSA folks access to diglib.org and we'll have a few new NDSA blog posts running over the next month (Innovation Awards interviews are finally about to come in) if we want to test an #ndsa Slack channel IFTTT script in the coming weeks.
