### ISSUE TITLE
Member Registration

### ISSUE THREAD

**Issue by waynegraham** [clirdlf/ndsa.org#9]
Create a Google form to handle registration

**Comment by ohbendorf** [comment]
I think this one is done - but not closing it yet in case you want to run a script to search for unique answer options and make sure we captured them all, @waynegraham

**Comment by ohbendorf** [comment]
I set the notification rules on the responses spreadsheet to send an email to dlfadm@gmail.com whenever someone signs up. @waynegraham, @nowviskie, is there another address you'd prefer? I couldn't figure out how to have it send a notification email to a non-Gmail address, though ndsa@diglib.org would be my preference, and didn't want them coming to my personal Gmail.

**Comment by waynegraham** [comment]
I think ndsa@diglib.org is fine

**Comment by nowviskie** [comment]
If it won't send to a non-Google account, why don't we create one for NDSA? You can have it forward to us for now and ultimately whomever will make sense -- but I'm guessing there will be other occasions when having one will be handy.

**Comment by ohbendorf** [comment]
New member applications will trigger a notification to ndsa.cal@gmail.com, which I've set up to forward to ndsa@diglib.org.
